"""
Not part of the running application - this generates
backend/scripts/seed_demo_data.sql. Kept around so the demo dataset can be
regenerated or extended later without hand-editing a wall of INSERT
statements. Deterministic (fixed seed) so re-running it produces identical
output.

Usage: python3 scripts/generate_seed_data.py > scripts/seed_demo_data.sql
"""
import random
from datetime import datetime, timedelta

random.seed(42)

customers = [
    ("Priya Nair", "priya.nair@example.com", "APAC"),
    ("Daniel Osei", "daniel.osei@example.com", "EMEA"),
    ("Maria Gonzalez", "maria.gonzalez@example.com", "LATAM"),
    ("Ethan Walker", "ethan.walker@example.com", "NA"),
    ("Sofia Rossi", "sofia.rossi@example.com", "EMEA"),
    ("Kenji Tanaka", "kenji.tanaka@example.com", "APAC"),
    ("Aaliyah Brown", "aaliyah.brown@example.com", "NA"),
    ("Lucas Mendes", "lucas.mendes@example.com", "LATAM"),
    ("Fatima Al-Sayed", "fatima.alsayed@example.com", "EMEA"),
    ("Grace Kim", "grace.kim@example.com", "APAC"),
    ("Noah Fischer", "noah.fischer@example.com", "EMEA"),
    ("Isabella Cruz", "isabella.cruz@example.com", "LATAM"),
    ("Liam O'Connor", "liam.oconnor@example.com", "NA"),
    ("Wei Zhang", "wei.zhang@example.com", "APAC"),
    ("Amara Okafor", "amara.okafor@example.com", "EMEA"),
]

products = [
    ("Aria Desk Lamp", "Lighting", 3499),
    ("Nimbus Office Chair", "Furniture", 24900),
    ("Slate Standing Desk", "Furniture", 39900),
    ("Pulse Wireless Mouse", "Electronics", 2999),
    ("Keystone Mechanical Keyboard", "Electronics", 8900),
    ("Drift Noise-Cancelling Headphones", "Electronics", 15900),
    ("Haven Desk Organizer", "Accessories", 1899),
    ("Contour Laptop Stand", "Accessories", 4499),
    ("Basecamp Backpack", "Bags", 7900),
    ("Fieldnote Notebook (3-pack)", "Stationery", 1299),
    ("Meridian Water Bottle", "Accessories", 2199),
    ("Orbit Webcam 1080p", "Electronics", 5499),
    ("Lumen Monitor Light Bar", "Lighting", 4299),
    ("Anchor Cable Organizer", "Accessories", 999),
    ("Vantage 27in Monitor", "Electronics", 22900),
    ("Trailhead Desk Mat", "Accessories", 2599),
    ("Compass Planner", "Stationery", 1899),
    ("Ridge Laptop Sleeve", "Bags", 3299),
]

statuses = ["completed", "completed", "completed", "completed", "refunded", "pending"]

start_date = datetime(2026, 1, 5)
end_date = datetime(2026, 7, 8)

orders = []
order_items = []
order_id = 1
item_id = 1

for cust_id in range(1, len(customers) + 1):
    num_orders = random.randint(1, 5)
    for _ in range(num_orders):
        days_offset = random.randint(0, (end_date - start_date).days)
        order_date = start_date + timedelta(days=days_offset, hours=random.randint(8, 20))
        status = random.choice(statuses)
        num_items = random.randint(1, 4)
        chosen = random.sample(products, num_items)
        total_cents = 0
        items_for_order = []
        for pname, pcat, pprice in chosen:
            prod_id = products.index((pname, pcat, pprice)) + 1
            qty = random.randint(1, 3)
            items_for_order.append((prod_id, qty, pprice))
            total_cents += qty * pprice
        orders.append((order_id, cust_id, order_date, status, total_cents))
        for prod_id, qty, price in items_for_order:
            order_items.append((item_id, order_id, prod_id, qty, price))
            item_id += 1
        order_id += 1


def esc(s):
    return s.replace("'", "''")


lines = []
lines.append("-- Loads the sample e-commerce dataset. Run scripts/schema.sql first.")
lines.append("-- Safe to re-run: TRUNCATEs and reloads deterministically (same random")
lines.append("-- seed every time), so demo data stays consistent across environments.")
lines.append("-- Generated by scripts/generate_seed_data.py - edit that, not this file directly.")
lines.append("")
lines.append("BEGIN;")
lines.append("")
lines.append("TRUNCATE order_items, orders, products, customers RESTART IDENTITY CASCADE;")
lines.append("")

lines.append("INSERT INTO customers (name, email, region, created_at) VALUES")
cust_rows = []
for name, email, region in customers:
    created = start_date - timedelta(days=random.randint(30, 400))
    cust_rows.append(f"  ('{esc(name)}', '{email}', '{region}', '{created.isoformat()}')")
lines.append(",\n".join(cust_rows) + ";")
lines.append("")

lines.append("INSERT INTO products (name, category, price_cents) VALUES")
prod_rows = [f"  ('{esc(name)}', '{cat}', {price})" for name, cat, price in products]
lines.append(",\n".join(prod_rows) + ";")
lines.append("")

lines.append("INSERT INTO orders (id, customer_id, created_at, status, total_cents) VALUES")
order_rows = [
    f"  ({oid}, {cid}, '{odate.isoformat()}', '{status}', {total})"
    for oid, cid, odate, status, total in orders
]
lines.append(",\n".join(order_rows) + ";")
lines.append("")

lines.append("INSERT INTO order_items (id, order_id, product_id, quantity, unit_price_cents) VALUES")
item_rows = [
    f"  ({iid}, {oid}, {pid}, {qty}, {price})" for iid, oid, pid, qty, price in order_items
]
lines.append(",\n".join(item_rows) + ";")
lines.append("")

lines.append("SELECT setval('orders_id_seq', (SELECT MAX(id) FROM orders));")
lines.append("SELECT setval('order_items_id_seq', (SELECT MAX(id) FROM order_items));")
lines.append("")
lines.append("COMMIT;")

print("\n".join(lines))
